services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - NGINX_PORT=80 # optional
      - WEB_APP_PORT=3000 # optional
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - /mnt/data/docker/netbootxyz/config:/config # optional
      - /mnt/data/docker/netbootxyz/assets:/assets # optional
    ports:
      - 3333:3000  # optional, destination should match ${WEB_APP_PORT} variable above.
      - 69:69/udp
      - 8083:80  # optional, destination should match ${NGINX_PORT} variable above.
    restart: unless-stopped
