version: "3.9"
services:
  gptwol:
    container_name: gptwol
    image: misterbabou/gptwol:latest
    network_mode: host
    restart: unless-stopped
    environment:
      - PORT=4287 #Free Port on Your host default is 5000
      - TZ=Europe/Vilnius #Set your timezone for Cron default is UTC
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
      #- DISABLE_ADD_DEL=1 #Uncomment this line to disable Add or delete Computers default is to allow
      #- DISABLE_REFRESH=1 #Uncomment this line to prevent your browser to refresh Computer status default is to allow
      #- REFRESH_PING=15 # Uncomment this line to change ping status check, can be 15 or 60 (seconds) default value is 30 seconds
      #- PING_TIMEOUT=200 #Uncomment this line to change the time to wait for a ping answer in (in ms) default value is 300 milliseconds
    volumes:
      - /mnt/data/docker/gptwol/computers.txt:/app/computers.txt
      - /mnt/data/docker/gptwol/appdata/cron:/etc/cron.d
