---
services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
      - SUBFOLDER=/ #optional
    volumes:
      - /mnt/data/docker/emulatorjs/config:/config
      - /mnt/data/docker/emulatorjs/data:/data
    ports:
      - 222:3000
      - 2280:80
      - 4001:4001 #optional
    restart: unless-stopped
