services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /mnt/data/docker/npm/data:/data
      - /mnt/data/docker/npm/etsencrypt:/etc/letsencrypt
