# Currently untested as written
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
      - VERSION=docker
      - PLEX_CLAIM= #optional
    ports:
      - 32400:32400
    devices:
     - /dev/dri:/dev/dri # QuickSync
    volumes:
      - /mnt/data/docker/plex:/config
      - /mnt/data:/data
    restart: unless-stopped
